-- Following / followers for the Protlys Hub social layer.
create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint follows_no_self check (follower_id <> following_id),
  constraint follows_unique_pair unique (follower_id, following_id)
);

create index if not exists follows_follower_idx on public.follows(follower_id, created_at desc);
create index if not exists follows_following_idx on public.follows(following_id, created_at desc);

alter table public.follows enable row level security;

drop policy if exists "Users can view follows" on public.follows;
drop policy if exists "Users can follow members" on public.follows;
drop policy if exists "Users can unfollow members" on public.follows;

create policy "Users can view follows"
  on public.follows for select using (true);
create policy "Users can follow members"
  on public.follows for insert
  with check (auth.uid() = follower_id and follower_id <> following_id);
create policy "Users can unfollow members"
  on public.follows for delete
  using (auth.uid() = follower_id);
