-- Batch 1: historical protein targets for accurate week views.
create table if not exists public.protein_target_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_g integer not null check (target_g between 20 and 500),
  source text not null default 'custom' check (source in ('calculator','custom')),
  effective_from date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists protein_target_history_user_date_idx
  on public.protein_target_history(user_id, effective_from desc, created_at desc);

alter table public.protein_target_history enable row level security;

drop policy if exists "Users can read own target history" on public.protein_target_history;
drop policy if exists "Users can insert own target history" on public.protein_target_history;

create policy "Users can read own target history"
  on public.protein_target_history for select using (auth.uid() = user_id);
create policy "Users can insert own target history"
  on public.protein_target_history for insert with check (auth.uid() = user_id);
