-- PROTLYS HUB — MIGRATION 011
-- Instagram-style comment interactions

alter table public.feed_comments
  add column if not exists parent_comment_id text;

create index if not exists idx_feed_comments_parent
  on public.feed_comments(parent_comment_id);

create table if not exists public.feed_comment_likes (
  id bigint generated by default as identity primary key,
  comment_id text not null,
  user_id uuid not null,
  created_at timestamptz not null default now(),
  unique(comment_id, user_id)
);

create index if not exists idx_feed_comment_likes_comment
  on public.feed_comment_likes(comment_id);

alter table public.feed_comment_likes enable row level security;

drop policy if exists "feed comment likes: read" on public.feed_comment_likes;
drop policy if exists "feed comment likes: insert own" on public.feed_comment_likes;
drop policy if exists "feed comment likes: delete own" on public.feed_comment_likes;

create policy "feed comment likes: read"
on public.feed_comment_likes
for select
to authenticated
using (true);

create policy "feed comment likes: insert own"
on public.feed_comment_likes
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "feed comment likes: delete own"
on public.feed_comment_likes
for delete
to authenticated
using ((select auth.uid()) = user_id);

alter table public.feed_comments enable row level security;
