import Link from 'next/link';
import '../globals.css';

const LOGO_SRC='/protlys-logo-exact.png?v=20260915';
const Section=({title,children})=><section style={{marginTop:22}}><h2 style={{fontSize:17,marginBottom:7}}>{title}</h2><div style={{fontSize:13,lineHeight:1.65,color:'var(--ink-70)'}}>{children}</div></section>;

export default function PrivacyPage(){
  return <div className="protlys-app"><main className="app-shell" style={{justifyContent:'flex-start',overflowY:'auto'}}><div className="screen-pad" style={{paddingTop:28,paddingBottom:48}}>
    <div style={{textAlign:'center',marginBottom:24}}><img src={LOGO_SRC} alt="Protlys" style={{width:150,height:'auto',objectFit:'contain'}}/></div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:18}}><Link href="/signup" style={{fontSize:12,fontWeight:800,color:'var(--green-dark)'}}>← Back to sign up</Link><Link href="/terms" style={{fontSize:12,fontWeight:800,color:'var(--green-dark)'}}>Terms & Conditions →</Link></div>
    <span className="eyebrow">Protlys Hub</span><h1 style={{fontSize:27,lineHeight:1.1}}>Privacy Policy</h1><p className="subhead">Last updated: 17 September 2026</p>
    <div style={{marginTop:16,background:'var(--green-soft)',border:'1px solid rgba(31,122,69,.12)',borderRadius:14,padding:'13px 14px',fontSize:12.5,lineHeight:1.55,color:'var(--green-dark)'}}>Protlys is building a practical digital layer around protein education, movement, habits and community. We want members to understand what information they share, why we use it and what choices they have.</div>
    <Section title="1. Who this policy applies to">This Privacy Policy applies to personal information processed through Protlys Hub and related Hub account, profile and community features. It should be read together with the Protlys Hub Terms & Conditions.</Section>
    <Section title="2. Our approach to personal data">Protlys aims to process personal data lawfully, fairly and transparently, for specified purposes and only to the extent reasonably necessary for those purposes. Kenya's Data Protection Act, 2019 provides data-subject rights including being informed about processing, access, correction, erasure, objection and restriction in applicable circumstances. The Office of the Data Protection Commissioner describes these principles and rights in its published guidance.</Section>
    <Section title="3. Information you provide">Depending on how you use the Hub, we may receive your name or display name, email address, password-related authentication information handled by our authentication provider, profile photo, bio, profile preferences, protein-target information, posts, comments, photos, follows, connections, challenge participation, event or community participation and other information you choose to submit.</Section>
    <Section title="4. Movement and activity information">If you use movement features, the Hub may process information such as steps, distance, duration, activity entries, dates, streaks and related calculations. Some activity information can become visible to other members when you choose to share it through your profile, feed, challenges or other community features. You should only share activity information you are comfortable making available through the relevant feature.</Section>
    <Section title="5. Information collected automatically">When you use the Hub, technical information may be processed to operate and secure the service. This can include browser or device information, IP address or similar network information, authentication events, pages or features used, error information and security-related logs. We use such information primarily for service operation, security, troubleshooting and improvement rather than to create an unrelated advertising profile about you.</Section>
    <Section title="6. Why we use information">We may use personal data to create and secure your account; authenticate you; provide profiles, feed, posts, comments, connections and follows; provide movement and habit features; calculate or save protein targets you request; support challenges and community activities; respond to support or privacy requests; maintain service security; prevent fraud, abuse and unauthorised access; troubleshoot and improve the Hub; comply with legal obligations; and communicate service-related information.</Section>
    <Section title="7. Legal bases">Depending on the circumstances, processing may be based on your consent, performance of a contract or steps taken at your request, compliance with a legal obligation, legitimate interests that do not override your rights, or another lawful basis recognised by applicable law. Where consent is relied on, you may withdraw it subject to legal and operational limitations.</Section>
    <Section title="8. Public profiles and community sharing">Protlys Hub is designed to include community interaction. Information you intentionally publish through a public profile, post, comment, photo, follow or shared profile feature may be visible to other members and may be copied by people who can see it. Protlys cannot guarantee what another person may do with information you voluntarily make visible. Before posting, consider whether the information should remain private.</Section>
    <Section title="9. Health and nutrition-related information">The Hub may allow you to enter or generate information related to protein targets, body weight, activity or other lifestyle information. We treat this information with care and use it for the feature you request and related service purposes. The Hub is not intended to diagnose, treat or monitor disease. If information you enter could reveal a health condition or other sensitive circumstance, only provide it where you understand the purpose and are comfortable doing so.</Section>
    <Section title="10. Who we may share information with">We may share personal data with service providers that process information on our behalf where necessary to operate the Hub, such as authentication, database, hosting, storage, security and communications providers. We may also disclose information where required by law, to protect rights or safety, to investigate abuse or security incidents, or as part of a lawful business transaction. We do not sell member personal data as a product to advertisers.</Section>
    <Section title="11. Authentication and account security">Protlys Hub uses an authentication service to manage account sign-in and passwords. Protlys does not need to see your password in order to operate your account. The application also uses database access controls intended to limit access to data according to the relevant user and feature. No internet service can promise absolute security, so you should use a unique password and protect access to your email and devices.</Section>
    <Section title="12. International processing">Some infrastructure or service providers may process data outside Kenya. Where personal data is transferred outside Kenya, Protlys will seek to apply the safeguards required by applicable data-protection law, including appropriate contractual, organisational or other safeguards where required.</Section>
    <Section title="13. Retention">We keep personal data for as long as reasonably necessary for the purpose for which it was collected, to operate your account and provide requested services, to meet legal or security requirements, or to resolve disputes. Retention periods can differ by data type. When information is no longer required, we aim to delete it, anonymise it or otherwise dispose of it appropriately, subject to lawful retention requirements.</Section>
    <Section title="14. Your data-protection rights">Subject to applicable law and relevant conditions, you may have rights to be informed about processing, access your personal data, request correction of inaccurate information, request erasure, object to certain processing, request restriction, and exercise other rights provided by law.</Section>
    <Section title="15. How to make a privacy request">For an access, correction, deletion, objection or other privacy request, use the current contact channels published by Protlys on its official website. Please describe the request clearly and provide enough information for us to verify the relevant account without sending unnecessary sensitive information. We may need to verify your identity before acting on a request.</Section>
    <Section title="16. Complaints">If you believe your personal data has been handled contrary to applicable law, you can first raise the matter with Protlys so we can investigate. You may also have the right to complain to the Office of the Data Protection Commissioner.</Section>
    <Section title="17. Children">Protlys Hub is not designed to knowingly collect personal data from children without an appropriate lawful basis and safeguards. If you are a parent or guardian and believe a child has provided personal data inappropriately, contact Protlys through its current official contact channel so the matter can be reviewed.</Section>
    <Section title="18. Cookies and similar technologies">The Hub may use essential browser storage, cookies or similar technologies needed for authentication, session management, security and basic functionality. Where non-essential technologies are introduced, Protlys will provide appropriate information and choices where required by applicable law.</Section>
    <Section title="19. Changes to this policy">We may update this Privacy Policy as the Hub, our processing practices or applicable requirements change. The latest version will be published on this page with its updated date. Material changes will be communicated through appropriate service channels where required.</Section>
    <Section title="20. Contact">For privacy questions or data-subject requests, use the current contact details published by Protlys through its official website. For complaints to the Kenyan data-protection regulator, use the official channels published by the Office of the Data Protection Commissioner.</Section>
    <div style={{marginTop:28,paddingTop:16,borderTop:'1px solid var(--line)',fontSize:11.5,color:'var(--ink-45)',lineHeight:1.55}}>This policy is written for the current Protlys Hub product and is intended to be reviewed and, where necessary, approved or amended by a Kenyan-qualified privacy lawyer before being treated as final legal advice or a complete compliance programme.</div>
  </div></main></div>;
}
