'use client';

import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { toBlob } from 'html-to-image';
import QRCode from 'qrcode';
import MemberShareCard from './MemberShareCard';

const LOOKS=['dark','light','surface'],LABELS={dark:'Dark',light:'Light',surface:'Surface'};
async function assetDataUrl(path){const r=await fetch(path,{cache:'force-cache'});if(!r.ok)throw new Error('Unable to load asset');const blob=await r.blob();return await new Promise((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(f.result);f.onerror=reject;f.readAsDataURL(blob)})}
function computeScale(){if(typeof window==='undefined')return 1;const w=(window.innerWidth-32)/360,h=(window.innerHeight-56-42-116-16)/640;return Math.max(.35,Math.min(1.2,w,h))}
async function waitImages(node){await Promise.all([...node.querySelectorAll('img')].map(async img=>{if(img.decode)try{await img.decode()}catch{}}))}

export default function MemberShareSheet({open,onClose,profileId,displayName,avatarUrl='',joinedAt='',founding=false,activeDays=[],totalSteps=0,currentStreak=0,bestStreak=0}){
 const [mounted,setMounted]=useState(false),[selected,setSelected]=useState('dark'),[assets,setAssets]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[scale,setScale]=useState(1);const host=useRef(null);
 useEffect(()=>setMounted(true),[]);
 useEffect(()=>{if(!open)return;setSelected('dark');setMessage('');setBusy(false);setScale(computeScale());const resize=()=>setScale(computeScale());window.addEventListener('resize',resize);window.addEventListener('orientationchange',resize);const old=document.body.style.overflow;document.body.style.overflow='hidden';(async()=>{try{const [logo,qr]=await Promise.all([assetDataUrl('/protlys-logo-exact.png'),QRCode.toDataURL('https://hub.protlys.com/member/'+profileId,{margin:1,width:220,errorCorrectionLevel:'M',color:{dark:'#111111',light:'#FFFFFF'}})]);setAssets({dark:logo,light:logo,surface:logo,qr})}catch(e){console.error('[Protlys Member Share]',e);setMessage('Some share assets could not be loaded.')}})();return()=>{window.removeEventListener('resize',resize);window.removeEventListener('orientationchange',resize);document.body.style.overflow=old}},[open,profileId]);
 async function exportBlob(){const source=host.current?.querySelector('[data-protlys-member-card="true"]');if(!source)throw new Error('Member card is not mounted.');const holder=document.createElement('div');holder.style.cssText='position:fixed;left:-30000px;top:0;width:360px;height:640px;overflow:hidden;pointer-events:none;';const clone=source.cloneNode(true);clone.style.transform='none';clone.style.width='360px';clone.style.height='640px';clone.style.overflow='hidden';holder.appendChild(clone);document.body.appendChild(holder);try{await document.fonts?.ready;await waitImages(clone);const blob=await toBlob(clone,{cacheBust:true,pixelRatio:2,width:360,height:640,style:{width:'360px',height:'640px',transform:'none',overflow:'hidden'}});if(!blob)throw new Error('Could not render card.');return blob}finally{holder.remove()}}
 async function share(){if(busy)return;setBusy(true);setMessage('');try{const blob=await exportBlob(),file=new File([blob],'protlys-member-card.png',{type:'image/png'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))await navigator.share({files:[file],title:displayName+' on Protlys'});else{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='protlys-member-card.png';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}}catch(e){if(e?.name!=='AbortError')setMessage('Could not share the card.')}finally{setBusy(false)}}
 async function save(){if(busy)return;setBusy(true);setMessage('');try{const blob=await exportBlob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='protlys-member-card.png';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);setMessage('Image saved.')}catch{setMessage('Could not save the card.')}finally{setBusy(false)}}
 async function copyLink(){try{await navigator.clipboard.writeText('https://hub.protlys.com/member/'+profileId);setMessage('Link copied.')}catch{setMessage('Could not copy the link.')}}
 if(!open||!mounted)return null;
 return createPortal(<div style={{position:'fixed',inset:0,zIndex:2147483000,fontFamily:'Manrope,sans-serif'}}><div aria-hidden="true" onClick={onClose} style={{position:'absolute',inset:0,background:'rgba(0,0,0,.6)'}}/><section ref={host} role="dialog" aria-modal="true" aria-label="Share your profile" style={{position:'absolute',inset:0,width:'100%',height:'100dvh',boxSizing:'border-box',padding:'max(env(safe-area-inset-top),12px) 16px calc(10px + env(safe-area-inset-bottom))',background:'#F7F8F6',color:'#111',display:'flex',flexDirection:'column',overflow:'hidden'}}>
  <div style={{height:56,flex:'0 0 56px',display:'flex',alignItems:'center',justifyContent:'space-between'}}><strong style={{fontSize:18}}>Share your profile</strong><button type="button" aria-label="Close share sheet" onClick={onClose} style={{width:48,height:48,border:'1px solid #D7DDD8',borderRadius:24,background:'#fff',fontSize:20}}>×</button></div>
  <div style={{flex:'1 1 auto',minHeight:0,display:'flex',alignItems:'center',justifyContent:'center',overflow:'hidden'}}><div style={{width:360*scale,height:640*scale,position:'relative',flex:'0 0 auto'}}><div style={{position:'absolute',left:0,top:0,width:360,height:640,transform:'scale('+scale+')',transformOrigin:'top left'}}><MemberShareCard displayName={displayName} username={displayName} avatarUrl={avatarUrl} joinedAt={joinedAt} founding={founding} activeDays={activeDays} totalSteps={totalSteps} currentStreak={currentStreak} bestStreak={bestStreak} look={selected} logoDataUrl={assets[selected]||'/protlys-logo-exact.png'} qrDataUrl={assets.qr||''}/></div></div></div>
  <div style={{height:52,flex:'0 0 52px',paddingTop:10,boxSizing:'border-box',display:'flex',gap:8,alignItems:'center',justifyContent:'center'}}>{LOOKS.map(look=><button key={look} type="button" aria-pressed={selected===look} onClick={()=>setSelected(look)} style={{height:42,minWidth:82,padding:'0 14px',border:'1px solid '+(selected===look?'#4F9F35':'#D7DDD8'),borderRadius:21,background:selected===look?(look==='light'?'#E9EFE7':'#323A33'):'#fff',color:selected===look?(look==='light'?'#111':'#fff'):'#111',fontSize:12,fontWeight:800}}>{LABELS[look]}</button>)}</div>
  <div style={{height:116,flex:'0 0 116px',display:'flex',flexDirection:'column',justifyContent:'flex-end',gap:8}}><button type="button" onClick={share} disabled={busy} style={{height:56,border:0,borderRadius:28,background:'#6BCB45',color:'#111',fontSize:14,fontWeight:900}}>↗ Share {LABELS[selected]} card</button><div style={{height:44,display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button type="button" onClick={save} disabled={busy} style={{height:44,border:'1px solid #AEB7B0',borderRadius:22,background:'#fff',fontSize:12,fontWeight:800}}>Save image</button><button type="button" onClick={copyLink} style={{height:44,border:'1px solid #AEB7B0',borderRadius:22,background:'#fff',fontSize:12,fontWeight:800}}>Copy link</button></div></div>
  {message&&<div role="status" style={{position:'absolute',left:16,right:16,bottom:'calc(124px + env(safe-area-inset-bottom))',textAlign:'center',fontSize:11,fontWeight:700,color:'#4F9F35'}}>{message}</div>}
 </section></div>,document.body);
}
