import Link from 'next/link';
import '../globals.css';

const LOGO_SRC='/protlys-logo-exact.png?v=20260915';

const Section=({title,children})=><section style={{marginTop:22}}><h2 style={{fontSize:17,marginBottom:7}}>{title}</h2><div style={{fontSize:13,lineHeight:1.65,color:'var(--ink-70)'}}>{children}</div></section>;

export default function TermsPage(){
  return <div className="protlys-app"><main className="app-shell" style={{justifyContent:'flex-start',overflowY:'auto'}}><div className="screen-pad" style={{paddingTop:28,paddingBottom:48}}>
    <div style={{textAlign:'center',marginBottom:24}}><img src={LOGO_SRC} alt="Protlys" style={{width:150,height:'auto',objectFit:'contain'}}/></div>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:18}}><Link href="/signup" style={{fontSize:12,fontWeight:800,color:'var(--green-dark)'}}>← Back to sign up</Link><Link href="/privacy" style={{fontSize:12,fontWeight:800,color:'var(--green-dark)'}}>Privacy Policy →</Link></div>
    <span className="eyebrow">Protlys Hub</span><h1 style={{fontSize:27,lineHeight:1.1}}>Terms & Conditions</h1><p className="subhead">Last updated: 17 September 2026</p>
    <div style={{marginTop:16,background:'var(--green-soft)',border:'1px solid rgba(31,122,69,.12)',borderRadius:14,padding:'13px 14px',fontSize:12.5,lineHeight:1.55,color:'var(--green-dark)'}}>Protlys Hub is the digital community and personal utility layer of Protlys. It is designed to help people learn about protein, track movement and habits, build a profile, participate in community activities and connect around a more active lifestyle.</div>
    <Section title="1. Acceptance of these terms">By creating an account, accessing Protlys Hub or using any Hub feature, you agree to these Terms & Conditions and the Protlys Privacy Policy. If you do not agree, do not create or use an account.</Section>
    <Section title="2. What Protlys Hub provides">The Hub may provide a personal profile, community feed, posts, comments, connections and follows, movement and activity tracking, challenges, events or community activities, protein education and calculators, profile sharing and other features introduced by Protlys. Features may change as the Hub develops.</Section>
    <Section title="3. Account responsibility">You are responsible for the information you provide, keeping your login credentials confidential and activity carried out through your account. Use a strong password and tell Protlys promptly if you believe your account has been accessed without permission. Do not create an account using another person's identity or impersonate another member.</Section>
    <Section title="4. Community and user content">You may post text, photographs, movement information and other content where the relevant feature allows it. You retain your rights in content you create, but you give Protlys permission to host, store, display and technically process that content as necessary to operate the Hub and the community features you choose to use. Do not post content that is unlawful, threatening, abusive, deceptive, defamatory, invasive of another person's privacy, sexually explicit, discriminatory, or intended to harm or exploit others. Do not upload another person's personal information or image without an appropriate basis or permission.</Section>
    <Section title="5. Public and shared profile information">Some information may be visible to other Hub members when you choose to use community features. Depending on the feature and your settings, this can include your display name, profile photo, bio, posts, photos, movement-related information, follows and other information you choose to share. Profile sharing is intended to let you control what you choose to present publicly; do not post information you need to keep private.</Section>
    <Section title="6. Protein, fitness and health information">Protlys Hub provides general educational information, calculators and habit-tracking tools. These features are not medical diagnosis, treatment or a substitute for advice from a qualified healthcare professional, registered dietitian or other appropriate professional. Protein targets and activity estimates are general estimates and may not be suitable for every person. If you have a medical condition, are pregnant or breastfeeding, are under medical care, or have specific dietary or nutritional needs, seek appropriate professional advice before making material changes to your diet or activity.</Section>
    <Section title="7. Movement and activity estimates">Movement features may use information such as steps, distance, duration or manually entered activity. Estimates can be affected by device limitations, user input and calculation methods. Protlys does not guarantee that any displayed estimate represents exact calories burned, distance, exercise intensity or physiological outcomes.</Section>
    <Section title="8. Challenges and community activities">Challenges and community activities are intended to encourage healthy habits and participation. They are not competitions for medical, financial or professional outcomes. Participate within your own abilities and follow venue, organiser and safety requirements for any physical activity or event. Protlys may pause, change or discontinue a challenge or community activity.</Section>
    <Section title="9. Products and Protlys brand">References to Protlys protein milk, yoghurt, beverages or other products are part of the broader Protlys ecosystem. Availability, pricing, ingredients, nutritional information, promotions and product formulations may change. Product information on the Hub should be read together with the information supplied with the relevant product.</Section>
    <Section title="10. Prohibited use">You must not attempt to bypass security controls, access another member's account or private information, scrape or harvest member data without permission, introduce malicious code, interfere with the service, misuse another person's content, or use the Hub for unlawful purposes. You must not use the Hub to provide professional medical advice while presenting yourself as Protlys or as a Protlys-endorsed professional unless expressly authorised.</Section>
    <Section title="11. Moderation and enforcement">Protlys may remove or restrict content, suspend features or restrict accounts where reasonably necessary to protect members, the service or legal rights, including where these Terms are breached. Where appropriate, Protlys may investigate reports of abuse, fraud, impersonation, security incidents or unlawful activity.</Section>
    <Section title="12. Availability and changes">The Hub is provided on an evolving basis. We may add, modify, suspend or discontinue features, including for maintenance, security, legal or product-development reasons. We will update these Terms when material changes are made. Continued use after an updated version takes effect means you accept the updated Terms, subject to any rights you have under applicable law.</Section>
    <Section title="13. Intellectual property">Protlys branding, logos, software, interface design, original educational material and other Protlys-created content are protected by applicable intellectual-property laws. You may use the Hub for its intended personal purposes but may not copy, reproduce, sell, distribute or commercially exploit Protlys materials without permission, except where applicable law permits otherwise.</Section>
    <Section title="14. Privacy">Personal data is handled as described in the Protlys Privacy Policy. The Privacy Policy explains what information the Hub may collect, why it is used, how it may be shared, retention considerations, security measures and the rights available to data subjects under applicable law, including Kenya's Data Protection Act, 2019.</Section>
    <Section title="15. Third-party services and links">The Hub may rely on third-party technology and services to provide authentication, hosting, storage, analytics or other functionality. Third-party services may have their own terms and privacy policies. Protlys is not responsible for independent third-party services outside its control.</Section>
    <Section title="16. Disclaimer and limitation">To the extent permitted by applicable law, Protlys provides the Hub and its general educational tools without a guarantee that every feature will always be available, error-free or suitable for every individual purpose. Nothing in these Terms excludes or limits a consumer right or other protection that cannot lawfully be excluded or limited under Kenyan law.</Section>
    <Section title="17. Governing law">These Terms are governed by the laws of Kenya, subject to any mandatory rights or remedies available to you under applicable law.</Section>
    <Section title="18. Contact">For questions about these Terms, account issues, privacy matters or reports concerning community content, use the current contact channels published by Protlys on its official website. We may request enough information to identify and address your request without asking you to disclose unnecessary personal information.</Section>
    <div style={{marginTop:28,paddingTop:16,borderTop:'1px solid var(--line)',fontSize:11.5,color:'var(--ink-45)',lineHeight:1.55}}>These Terms are intended as a practical product policy for Protlys Hub and should be reviewed by a Kenyan-qualified lawyer before being treated as final legal advice for the business.</div>
  </div></main></div>;
}
