'use client';

import { Suspense, useRef, useState, useEffect } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import '../globals.css';

const EyeIcon=({open})=>open?<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>:<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/><line x1="1" y1="1" x2="23" y2="23"/></svg>;
function Logo(){return <div style={{textAlign:'center',marginBottom:32}}><img src="/protlys-logo.svg" alt="Protlys" style={{width:180,height:'auto',objectFit:'contain'}}/></div>}
const errStyle={background:'#FEE2E2',borderRadius:10,padding:'10px 14px',fontSize:13,color:'#B3261E',marginBottom:10};
const linkStyle={background:'none',border:'none',color:'var(--green-dark)',fontWeight:700,fontSize:13,cursor:'pointer',padding:0};
const googleBtnStyle={width:'100%',display:'flex',alignItems:'center',justifyContent:'center',gap:10,background:'#fff',border:'1.5px solid var(--line)',borderRadius:12,padding:'13px 16px',fontSize:14,fontWeight:600,cursor:'pointer',color:'var(--ink)',marginTop:20,fontFamily:'inherit'};
const dividerStyle={display:'flex',alignItems:'center',gap:12,margin:'18px 0',color:'var(--ink-45)',fontSize:13,fontWeight:600};
const Spinner=({text='Please wait…'})=><span style={{display:'flex',alignItems:'center',justifyContent:'center',gap:8}}><span style={{width:16,height:16,border:'2px solid rgba(255,255,255,.4)',borderTopColor:'#fff',borderRadius:'50%',animation:'spin .7s linear infinite',display:'inline-block'}}/>{text}</span>;

function normalizePhone(value){const raw=String(value||'').trim().replace(/[\s()-]/g,'');if(raw.startsWith('07'))return `+254${raw.slice(1)}`;if(raw.startsWith('7'))return `+254${raw}`;return raw;}

function LoginPageContent(){
 const searchParams=useSearchParams();const emailRef=useRef();const passwordRef=useRef();const resetRef=useRef();const phoneRef=useRef();const otpRef=useRef();
 const [showPw,setShowPw]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [mode,setMode]=useState('login');const [resetSentTo,setResetSentTo]=useState('');const [confirmationEmail,setConfirmationEmail]=useState('');const [confirmationSent,setConfirmationSent]=useState(false);const [phoneStep,setPhoneStep]=useState('phone');const [phone,setPhone]=useState('');
 const rawNext=searchParams.get('next');const nextPath=rawNext&&rawNext.startsWith('/')&&!rawNext.startsWith('//')?rawNext:'/';
 useEffect(()=>{const callbackError=searchParams.get('error_message');if(callbackError)setError(decodeURIComponent(callbackError));},[searchParams]);
 async function handleLogin(e){e.preventDefault();setError('');setConfirmationSent(false);setLoading(true);const email=emailRef.current.value.trim().toLowerCase(),password=passwordRef.current.value;const supabase=createClient();const {error}=await supabase.auth.signInWithPassword({email,password});setLoading(false);if(error){const msg=error.message||'Unable to log in.';if(/email not confirmed/i.test(msg)){setConfirmationEmail(email);setError('Your email has not been confirmed yet.');}else if(/invalid login credentials/i.test(msg))setError('Email or password is incorrect.');else setError(msg);return;}window.location.assign(nextPath);}
 async function resendConfirmation(){if(!confirmationEmail)return;setError('');setLoading(true);const supabase=createClient();const {error}=await supabase.auth.resend({type:'signup',email:confirmationEmail,options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=${encodeURIComponent(nextPath)}`}});setLoading(false);if(error){setError(error.message);return;}setConfirmationSent(true);}
 async function handleGoogle(){setError('');const supabase=createClient();const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/auth/callback?next=${encodeURIComponent(nextPath)}`}});if(error)setError(error.message);}
 async function handleForgot(e){e.preventDefault();setError('');setLoading(true);const supabase=createClient();const email=resetRef.current.value.trim().toLowerCase();const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});setLoading(false);if(error){setError(error.message);return;}setResetSentTo(email);setMode('forgot-sent');}
 async function sendPhoneOtp(){const normalized=normalizePhone(phoneRef.current?.value||phone);if(!/^\+\d{8,15}$/.test(normalized)){setError('Enter a valid mobile number, e.g. +254 712 345 678.');return;}setPhone(normalized);setError('');setLoading(true);const supabase=createClient();const {error}=await supabase.auth.signInWithOtp({phone:normalized,options:{shouldCreateUser:false}});setLoading(false);if(error){setError(error.message);return;}setPhoneStep('otp');}
 async function verifyPhoneOtp(e){e.preventDefault();const token=otpRef.current?.value?.trim();if(!/^\d{6}$/.test(token)){setError('Enter the 6-digit code sent to your phone.');return;}setError('');setLoading(true);const supabase=createClient();const {error}=await supabase.auth.verifyOtp({phone,token,type:'sms'});setLoading(false);if(error){setError(error.message);return;}window.location.assign(nextPath);}
 if(mode==='forgot-sent')return <Shell><Logo/><div style={{textAlign:'center'}}><div style={{fontSize:48,marginBottom:12}}>✓</div><h1 style={{fontSize:22}}>Check your inbox</h1><p className="subhead" style={{marginTop:8}}>Reset link sent to <strong>{resetSentTo}</strong>.</p><button className="btn-secondary" style={{marginTop:20}} onClick={()=>{setMode('login');setError('')}}>Back to log in</button></div></Shell>;
 if(mode==='forgot')return <Shell><Logo/><span className="eyebrow">Reset password</span><h1 style={{fontSize:22}}>Forgot your password?</h1><p className="subhead" style={{marginTop:6}}>We'll send a reset link to your email.</p><form onSubmit={handleForgot} style={{marginTop:20}}><div className="field-group"><label className="field-label">EMAIL</label><input ref={resetRef} type="email" required className="field-input" placeholder="Enter your email" autoComplete="email"/></div>{error&&<div style={errStyle}>{error}</div>}<button className="btn-primary" type="submit" disabled={loading}>{loading?'Sending…':'Send reset link'}</button></form><p style={{textAlign:'center',marginTop:18,fontSize:14}}><button onClick={()=>{setMode('login');setError('')}} style={linkStyle}>← Back to log in</button></p></Shell>;
 if(mode==='phone')return <Shell><Logo/><span className="eyebrow">Phone sign in</span><h1 style={{fontSize:22}}>{phoneStep==='phone'?'Log in with your phone':'Enter your code'}</h1><p className="subhead">{phoneStep==='phone'?'We’ll send a one-time code by SMS.':'Enter the 6-digit code sent to '+phone+'.'}</p>{phoneStep==='phone'?<><div className="field-group" style={{marginTop:20}}><label className="field-label">MOBILE NUMBER</label><input ref={phoneRef} type="tel" className="field-input" placeholder="+254 712 345 678" autoComplete="tel" defaultValue={phone}/></div>{error&&<div style={errStyle}>{error}</div>}<button className="btn-primary" onClick={sendPhoneOtp} disabled={loading}>{loading?<Spinner text="Sending code…"/>:'Send code'}</button></>:<form onSubmit={verifyPhoneOtp} style={{marginTop:20}}><div className="field-group"><label className="field-label">SMS CODE</label><input ref={otpRef} inputMode="numeric" maxLength={6} className="field-input" placeholder="123456" autoComplete="one-time-code"/></div>{error&&<div style={errStyle}>{error}</div>}<button className="btn-primary" type="submit" disabled={loading}>{loading?<Spinner text="Verifying…"/>:'Verify and log in'}</button><button type="button" className="btn-secondary" style={{marginTop:10}} onClick={()=>{setPhoneStep('phone');setError('')}}>Use a different number</button></form>}<p style={{textAlign:'center',marginTop:18,fontSize:14}}><button onClick={()=>{setMode('login');setPhoneStep('phone');setError('')}} style={linkStyle}>← Back to email</button></p></Shell>;
 return <Shell><Logo/><span className="eyebrow">Welcome back</span><h1 style={{fontSize:22}}>Log in to your Hub</h1><button type="button" onClick={handleGoogle} style={googleBtnStyle}>Continue with Google</button><div style={dividerStyle}><span>or</span></div><form onSubmit={handleLogin}><div className="field-group"><label className="field-label">EMAIL</label><input ref={emailRef} type="email" required className="field-input" placeholder="Enter your email" autoComplete="email"/></div><div className="field-group"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:6}}><label className="field-label" style={{marginBottom:0}}>PASSWORD</label><button type="button" onClick={()=>{setMode('forgot');setError('')}} style={linkStyle}>Forgot password?</button></div><div style={{position:'relative'}}><input ref={passwordRef} type={showPw?'text':'password'} required className="field-input" placeholder="Enter your password" autoComplete="current-password" style={{paddingRight:88}}/><button type="button" onClick={()=>setShowPw(v=>!v)} style={{position:'absolute',right:10,top:'50%',transform:'translateY(-50%)',background:'none',border:'none',cursor:'pointer',color:'var(--green-dark)',display:'flex',alignItems:'center',gap:5,padding:'6px 4px',fontFamily:'inherit',fontSize:12,fontWeight:700}}><EyeIcon open={showPw}/><span>{showPw?'Hide':'Show'}</span></button></div></div>{error&&<div style={errStyle}>{error}</div>}{confirmationEmail&&<div style={{background:'var(--green-soft)',borderRadius:10,padding:'10px 14px',fontSize:13,color:'var(--green-dark)',marginBottom:10}}>{confirmationSent?<>Confirmation email sent to <strong>{confirmationEmail}</strong>.</>:<button type="button" onClick={resendConfirmation} disabled={loading} style={{...linkStyle,fontSize:13}}>Resend confirmation email</button>}</div>}<button className="btn-primary" type="submit" disabled={loading}>{loading?<Spinner text="Logging in…"/>:'Log in'}</button></form><button type="button" onClick={()=>{setMode('phone');setPhoneStep('phone');setError('')}} style={{...googleBtnStyle,marginTop:12}}>Use phone number</button><p style={{textAlign:'center',marginTop:18,fontSize:14,color:'var(--ink-70)'}}>New to Protlys? <Link href="/signup" style={{color:'var(--green-dark)',fontWeight:700}}>Create an account</Link></p></Shell>;
}
function Shell({children}){return <div className="protlys-app"><div className="app-shell" style={{justifyContent:'flex-start',overflowY:'auto'}}><div className="screen-pad" style={{paddingTop:40,paddingBottom:40}}>{children}</div></div><style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style></div>}
export default function LoginPage(){return <Suspense fallback={<div>Loading…</div>}><LoginPageContent/></Suspense>}
