import { notFound, redirect } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import AppShell from '@/components/AppShell';
import MemberPostComments from '@/app/MemberPostComments';
import MovementActivity from '@/components/MovementActivity';
import ProfileSectionNav from '@/components/ProfileSectionNav';
import ProfileSectionSlider from '@/components/ProfileSectionSlider';
import FollowButton from '@/components/FollowButton';
import ShareProfileButton from '@/components/ShareProfileButton';

function Avatar({ name, url, size = 72 }) { const style={width:size,height:size,minWidth:size,minHeight:size,aspectRatio:'1 / 1',borderRadius:'50%',objectFit:'cover',display:'block',flexShrink:0}; if(url)return <img src={url} alt="" style={style}/>; return <div style={{...style,background:'var(--green-soft)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:size*.34,fontWeight:800,color:'var(--green-dark)'}}>{(name||'?')[0].toUpperCase()}</div>; }
function Icon({name,size=17}) { const paths={arrow:<path d="M19 12H5m6-6-6 6 6 6"/>}; return <svg viewBox="0 0 24 24" width={size} height={size} fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>; }
function parseProtlysDate(value){if(!value)return null;const raw=String(value);const normalized=/(?:Z|[+-]\d{2}:?\d{2})$/i.test(raw)?raw:`${raw}Z`;const date=new Date(normalized);return Number.isNaN(date.getTime())?null:date;}
function formatNairobiDate(value){const date=parseProtlysDate(value);if(!date)return 'Date unavailable';return new Intl.DateTimeFormat('en-KE',{timeZone:'Africa/Nairobi',day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true}).format(date);}
function formatJoinedDate(value){const date=parseProtlysDate(value);if(!date)return 'Joined date unavailable';return new Intl.DateTimeFormat('en-KE',{timeZone:'Africa/Nairobi',day:'numeric',month:'long',year:'numeric'}).format(date);}
function PostStats({stats}){if(!stats||typeof stats!=='object')return null;const items=[['Steps',stats.steps],['Distance',stats.distance],['Duration',stats.duration]].filter(([,value])=>value!==null&&value!==undefined&&String(value).trim()!=='');if(!items.length)return null;return <div style={{display:'grid',gridTemplateColumns:`repeat(${Math.min(items.length,3)},minmax(0,1fr))`,gap:7,margin:'10px 0 2px'}}>{items.map(([label,value])=><div key={label} style={{border:'1px solid var(--line)',borderRadius:10,padding:'8px 9px',background:'var(--paper)',minWidth:0}}><div style={{fontSize:8.5,textTransform:'uppercase',letterSpacing:'.06em',fontWeight:800,color:'var(--ink-45)'}}>{label}</div><div className="mono" style={{fontSize:12,fontWeight:800,color:'var(--ink)',marginTop:2,overflowWrap:'anywhere'}}>{value}</div></div>)}</div>;}

export default async function MemberProfilePage({params}){
  const {id}=await params; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/login');
  const [{data:profile},{data:posts},{count:postCount},{data:achievements},{data:movementDays},{count:followerCount},{count:followingCount},{data:followRow}]=await Promise.all([
    supabase.from('profiles').select('id, display_name, avatar_url, bio, created_at, streak, step_streak, total_steps, step_goal, target_g').eq('id',id).maybeSingle(),
    supabase.from('feed_posts').select('id, body, image_url, post_type, stats, created_at, feed_likes(count), feed_comments(count)').eq('user_id',id).order('created_at',{ascending:false}).limit(30),
    supabase.from('feed_posts').select('id',{count:'exact',head:true}).eq('user_id',id),
    supabase.from('user_achievements').select('earned_at, achievements(slug, name, icon, description)').eq('user_id',id).order('earned_at',{ascending:false}).limit(6),
    supabase.from('daily_steps').select('step_date, steps').eq('user_id',id).gt('steps',0).order('step_date',{ascending:true}),
    supabase.from('follows').select('id',{count:'exact',head:true}).eq('following_id',id),
    supabase.from('follows').select('id',{count:'exact',head:true}).eq('follower_id',id),
    supabase.from('follows').select('id').eq('follower_id',user.id).eq('following_id',id).maybeSingle(),
  ]);
  if(!profile)notFound(); const displayName=profile.display_name?.trim()||'Protlys Member'; const photoPosts=(posts||[]).filter(post=>post.image_url); const isOwnProfile=String(user.id)===String(id); const bio=profile.bio?.trim()||'';
  return <AppShell><style>{`html{scroll-behavior:smooth}.profile-section-slider::-webkit-scrollbar{display:none}`}</style><div className="screen-pad" style={{paddingTop:14}}>
    <Link href="/" style={{display:'inline-flex',alignItems:'center',gap:7,color:'var(--ink-70)',textDecoration:'none',fontSize:12,fontWeight:800,marginBottom:10}}><Icon name="arrow" size={16}/> Back to Feed</Link>
    <section style={{background:'#fff',border:'1.5px solid var(--line)',borderRadius:20,padding:'16px 14px 13px',boxShadow:'0 2px 8px rgba(0,0,0,.035)'}}>
      <div style={{display:'flex',alignItems:'center',gap:12}}><Avatar name={displayName} url={profile.avatar_url}/><div style={{minWidth:0,flex:1}}><div className="eyebrow">Protlys member</div><h1 style={{fontSize:21,margin:'2px 0 0',lineHeight:1.12,overflowWrap:'anywhere'}}>{displayName}</h1></div><div style={{display:'flex',alignItems:'center',gap:7,flexShrink:0}}><ShareProfileButton profileId={id} displayName={displayName}/>{!isOwnProfile&&<FollowButton profileId={id} initialFollowing={Boolean(followRow)} initialFollowers={followerCount||0} compact/>}</div></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',marginTop:13,borderTop:'1px solid var(--line)',borderBottom:'1px solid var(--line)',padding:'10px 0'}}>
        <Link href={`/member/${id}`} style={{textAlign:'center',textDecoration:'none',color:'var(--ink)',borderRight:'1px solid var(--line)'}}><div className="mono" style={{fontSize:16,fontWeight:800}}>{postCount||0}</div><div style={{fontSize:9,textTransform:'uppercase',letterSpacing:'.05em',fontWeight:800,color:'var(--ink-45)',marginTop:2}}>Posts</div></Link>
        <Link href={`/member/${id}/connections?type=followers`} style={{textAlign:'center',textDecoration:'none',color:'var(--ink)',borderRight:'1px solid var(--line)'}}><div className="mono" style={{fontSize:16,fontWeight:800}}>{followerCount||0}</div><div style={{fontSize:9,textTransform:'uppercase',letterSpacing:'.05em',fontWeight:800,color:'var(--ink-45)',marginTop:2}}>Followers</div></Link>
        <Link href={`/member/${id}/connections?type=following`} style={{textAlign:'center',textDecoration:'none',color:'var(--ink)'}}><div className="mono" style={{fontSize:16,fontWeight:800}}>{followingCount||0}</div><div style={{fontSize:9,textTransform:'uppercase',letterSpacing:'.05em',fontWeight:800,color:'var(--ink-45)',marginTop:2}}>Following</div></Link>
      </div>
      {bio&&<div style={{paddingTop:11,fontSize:13,lineHeight:1.45,color:'var(--ink-70)',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{bio}</div>}
      <div style={{fontSize:10.5,color:'var(--ink-45)',fontWeight:700,marginTop:bio?8:10}}>Joined {formatJoinedDate(profile.created_at)}</div>
    </section>
    <ProfileSectionNav/>
    <ProfileSectionSlider>
      <section id="posts" style={{flex:'0 0 100%',minWidth:0,scrollSnapAlign:'start',scrollMarginTop:140,paddingTop:8,paddingBottom:6}}><div className="eyebrow" style={{marginBottom:8}}>Posts</div>{posts?.length?posts.map(post=><article key={post.id} className="profile-post-card" style={{background:'#fff',border:'1.5px solid var(--line)',borderRadius:16,padding:14,marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',gap:10,marginBottom:7}}><span style={{fontSize:10.5,color:'var(--ink-45)'}}>{formatNairobiDate(post.created_at)}</span>{post.post_type&&post.post_type!=='general'&&<span style={{background:'var(--green-soft)',color:'var(--green-dark)',padding:'2px 7px',borderRadius:999,fontSize:10,fontWeight:800}}>{post.post_type.replace('_',' ')}</span>}</div>{post.body&&<p style={{fontSize:13.5,lineHeight:1.55,margin:'0 0 10px'}}>{post.body}</p>}<PostStats stats={post.stats}/>{post.image_url&&<img src={post.image_url} alt="" style={{width:'100%',maxHeight:280,objectFit:'cover',borderRadius:12,display:'block',marginTop:post.stats?10:0}}/>}<MemberPostComments postId={post.id} initialCount={post.feed_comments?.[0]?.count||0} initialLikeCount={post.feed_likes?.[0]?.count||0}/></article>):<div style={{background:'#fff',border:'1.5px solid var(--line)',borderRadius:16,padding:'28px 18px',textAlign:'center'}}><div style={{fontWeight:800}}>No posts yet</div><p className="subhead" style={{margin:'5px 0 0'}}>This member has not shared anything to the feed.</p></div>}</section>
      <section id="stats" style={{flex:'0 0 100%',minWidth:0,scrollSnapAlign:'start',scrollMarginTop:140,paddingTop:8,paddingBottom:6}}><div className="eyebrow" style={{marginBottom:8}}>Stats & movement</div><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:8,marginBottom:12}}><div style={{background:'#fff',border:'1.5px solid var(--line)',borderRadius:14,padding:14}}><div style={{fontSize:9,textTransform:'uppercase',letterSpacing:'.06em',fontWeight:800,color:'var(--ink-45)'}}>Step streak</div><div className="mono" style={{fontSize:22,fontWeight:800,marginTop:4}}>{profile.step_streak||0}</div></div><div style={{background:'#fff',border:'1.5px solid var(--line)',borderRadius:14,padding:14}}><div style={{fontSize:9,textTransform:'uppercase',letterSpacing:'.06em',fontWeight:800,color:'var(--ink-45)'}}>Total steps</div><div className="mono" style={{fontSize:22,fontWeight:800,marginTop:4}}>{Number(profile.total_steps||0).toLocaleString()}</div></div></div><MovementActivity days={movementDays||[]} title={`${displayName}'s movement`}/>{achievements?.length>0&&<section style={{marginTop:14}}><div className="eyebrow" style={{marginBottom:8}}>Milestones</div><div style={{display:'flex',gap:8,overflowX:'auto',paddingBottom:2}}>{achievements.map(item=><div key={`${item.achievements?.slug}-${item.earned_at}`} style={{flex:'0 0 auto',border:'1px solid var(--line)',borderRadius:12,padding:'10px 12px',background:'#fff',minWidth:150}}><div style={{fontSize:12,fontWeight:800}}>{item.achievements?.name||'Milestone'}</div>{item.achievements?.description&&<div style={{fontSize:10.5,color:'var(--ink-45)',marginTop:3}}>{item.achievements.description}</div>}</div>)}</div></section>}</section>
      <section id="photos" style={{flex:'0 0 100%',minWidth:0,scrollSnapAlign:'start',scrollMarginTop:140,paddingTop:8,paddingBottom:24}}><div className="eyebrow" style={{marginBottom:8}}>Photos</div>{photoPosts.length?<div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:5}}>{photoPosts.map(post=><a key={post.id} href={`#photo-${post.id}`} style={{display:'block',aspectRatio:'1 / 1',overflow:'hidden',borderRadius:10,background:'var(--paper)'}}><img src={post.image_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover',display:'block'}}/></a>)}</div>:<div style={{background:'#fff',border:'1.5px solid var(--line)',borderRadius:16,padding:'28px 18px',textAlign:'center'}}><div style={{fontWeight:800}}>No photos yet</div><p className="subhead" style={{margin:'5px 0 0'}}>Photos shared by this member will appear here.</p></div>}</section>
    </ProfileSectionSlider>
  </div></AppShell>;
}
